Class = require("lib.middleclass")
require("nebulae.GraphicsManager")
require("nebulae.Project")
require("nebulae.Player")
require("nebulae.Renderer")
TextRender = require("nebulae.TextRender")
ProjectPluginManager = require("nebulae.ProjectPluginManager")
require("nebulae.AudioManager")
require("nebulae.KeyframeManager")