name: build nebulae

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  fuse:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: download love 12.0
        run: |
          curl -L -o love-win64.zip https://coolestperson.me/public/love-12.0-win64.zip

      - name: unzip love 12.0
        run: |
          unzip love-win64.zip -d love12

      - name: create love archive
        run: |
          zip -r game.love *.lua src ui lib config

      - name: fuse love file to exe
        run: |
          mkdir build
          cat love12/love.exe game.love > build/Nebulae.exe  # Fuse Nebulae.exe with game.love

      - name: copy dlls and folders
        run: |
          cp love12/*.dll build/
          cp -r assets build/
          cp -r plugins build/

      - name: upload artifact
        uses: actions/upload-artifact@main
        with:
          name: Nebulae
          path: build/
